// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversidadJCE1.Context;

#nullable disable

namespace UniversidadJCE1.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversidadJCE1.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<int>("CursoDetalleId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<int?>("ProfesoresProfesorId")
                        .HasColumnType("int");

                    b.HasKey("CursoId");

                    b.HasIndex("ProfesoresProfesorId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("UniversidadJCE1.Models.CursoDetalle", b =>
                {
                    b.Property<int>("CursoDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoDetalleId"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.HasKey("CursoDetalleId");

                    b.HasIndex("CursoId");

                    b.HasIndex("EstudianteId")
                        .IsUnique();

                    b.ToTable("CursoDetalles");
                });

            modelBuilder.Entity("UniversidadJCE1.Models.Estudiantes", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstudianteId");

                    b.HasIndex("CursoId")
                        .IsUnique();

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("UniversidadJCE1.Models.Profesores", b =>
                {
                    b.Property<int>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfesorId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfesorId");

                    b.ToTable("Profesores");
                });

            modelBuilder.Entity("UniversidadJCE1.Models.Curso", b =>
                {
                    b.HasOne("UniversidadJCE1.Models.Profesores", "Profesores")
                        .WithMany("Curso")
                        .HasForeignKey("ProfesoresProfesorId");

                    b.Navigation("Profesores");
                });

            modelBuilder.Entity("UniversidadJCE1.Models.CursoDetalle", b =>
                {
                    b.HasOne("UniversidadJCE1.Models.Curso", "Curso")
                        .WithMany("CursoDetalle")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversidadJCE1.Models.Estudiantes", "Estudiante")
                        .WithOne("CursoDetalles")
                        .HasForeignKey("UniversidadJCE1.Models.CursoDetalle", "EstudianteId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("UniversidadJCE1.Models.Estudiantes", b =>
                {
                    b.HasOne("UniversidadJCE1.Models.Curso", "Curso")
                        .WithOne("Estudiantes")
                        .HasForeignKey("UniversidadJCE1.Models.Estudiantes", "CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("UniversidadJCE1.Models.Curso", b =>
                {
                    b.Navigation("CursoDetalle");

                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("UniversidadJCE1.Models.Estudiantes", b =>
                {
                    b.Navigation("CursoDetalles");
                });

            modelBuilder.Entity("UniversidadJCE1.Models.Profesores", b =>
                {
                    b.Navigation("Curso");
                });
#pragma warning restore 612, 618
        }
    }
}
